[package]
name = "lock-me-window"
version = "0.2.0"
edition = "2024"
license = "MIT"

[dependencies]
raw-window-handle = "0.6.2"
rfd = "0.17.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
slint = { version = "1.17.1", features = ["raw-window-handle-06"] }
sys-locale = "0.3.2"
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_LibraryLoader",
    "Win32_System_Registry",
    "Win32_System_Threading",
    "Win32_UI_Accessibility",
    "Win32_UI_Controls",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
slint-build = "1.17.1"
winresource = { version = "0.1.31", default-features = false }

[profile.release]
strip = true

[[bin]]
name = "lock-me-window"
path = "src/main.rs"
test = false
bench = false
